---
title: Ediflo
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Test
footer-description: Test
email: connect@axonista.com
baseurl:
markdown: kramdown

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
